# Generated by Django 5.0.2 on 2025-05-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='level_test_completed',
            field=models.BooleanField(default=False, verbose_name='레벨 테스트 완료 여부'),
        ),
    ]
