# Generated by Django 5.0.2 on 2025-05-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='streak_days',
            field=models.IntegerField(default=1),
        ),
    ]
