# Generated by Django 5.0.2 on 2025-05-14 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_is_teacher_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='target_study_time',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_words_per_day',
            field=models.IntegerField(default=20),
        ),
    ]
