# Generated by Django 5.0.2 on 2025-05-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_target_study_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='streak_days',
            field=models.IntegerField(default=0, verbose_name='연속 학습일'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_achievement_rate',
            field=models.IntegerField(default=0, verbose_name='주간 달성률'),
        ),
    ]
