# Generated by Django 5.0.2 on 2025-05-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_streak_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_study_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
