# Generated by Django 5.0.2 on 2025-05-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_last_study_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '프로필', 'verbose_name_plural': '프로필'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_study_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_words_per_day',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_study_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_words_learned',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='weekly_achievement_rate',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level_test_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_goal',
            field=models.IntegerField(default=10, verbose_name='일일 목표'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_study_date',
            field=models.DateField(blank=True, null=True, verbose_name='마지막 학습일'),
        ),
    ]
