# Generated by Django 5.0.2 on 2025-05-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(choices=[(1, '초보자'), (2, '학습자'), (3, '중급자'), (4, '상급자'), (5, '전문가')], default=1, verbose_name='레벨'),
        ),
    ]
