# Generated by Django 5.0.2 on 2025-05-21 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_level_up_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 레벨업 날짜'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0, verbose_name='포인트'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points_to_next_level',
            field=models.IntegerField(default=100, verbose_name='다음 레벨까지 필요한 포인트'),
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='포인트')),
                ('reason', models.CharField(max_length=100, verbose_name='사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='획득일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '포인트 기록',
                'verbose_name_plural': '포인트 기록 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
