# Generated by Django 5.0.2 on 2025-03-21 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocabulary', '0002_alter_word_options_alter_wordstudyhistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='퀴즈 제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('quiz_type', models.CharField(choices=[('en_to_ko', '영한 퀴즈'), ('ko_to_en', '한영 퀴즈'), ('multiple', '객관식'), ('typing', '단어 입력')], max_length=20, verbose_name='퀴즈 유형')),
                ('difficulty', models.CharField(choices=[('easy', '쉬움'), ('medium', '보통'), ('hard', '어려움')], max_length=10, verbose_name='난이도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('time_limit', models.IntegerField(default=0, verbose_name='제한 시간(분)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '퀴즈',
                'verbose_name_plural': '퀴즈 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작 시간')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시간')),
                ('score', models.IntegerField(default=0, verbose_name='점수')),
                ('total_questions', models.IntegerField(default=0, verbose_name='전체 문제 수')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='정답 수')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='quiz.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '퀴즈 응시 기록',
                'verbose_name_plural': '퀴즈 응시 기록 목록',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='문제 순서')),
                ('option1', models.CharField(blank=True, max_length=200, verbose_name='보기 1')),
                ('option2', models.CharField(blank=True, max_length=200, verbose_name='보기 2')),
                ('option3', models.CharField(blank=True, max_length=200, verbose_name='보기 3')),
                ('option4', models.CharField(blank=True, max_length=200, verbose_name='보기 4')),
                ('correct_option', models.IntegerField(default=1, verbose_name='정답 번호')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='vocabulary.word')),
            ],
            options={
                'verbose_name': '퀴즈 문제',
                'verbose_name_plural': '퀴즈 문제 목록',
                'ordering': ['quiz', 'order'],
                'unique_together': {('quiz', 'order')},
            },
        ),
        migrations.CreateModel(
            name='QuizAnswerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=200, verbose_name='사용자 답안')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답 여부')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='답변 시간')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_history', to='quiz.quizattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_history', to='quiz.quizquestion')),
            ],
            options={
                'verbose_name': '퀴즈 답안 기록',
                'verbose_name_plural': '퀴즈 답안 기록 목록',
                'ordering': ['attempt', 'question__order'],
            },
        ),
    ]
