# Generated by Django 5.0.2 on 2025-03-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='user_answer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='사용자 답안'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True, verbose_name='정답 여부'),
        ),
    ] 