# Generated by Django 5.0.2 on 2025-03-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_add_user_answer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='정답 여부'),
        ),
    ]
