# Generated by Django 5.0.2 on 2025-05-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_quizattempt_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='mode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
