# Generated by Django 5.0.2 on 2025-05-20 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizattempt_mode_quizattempt_quiz_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wronganswernote',
            name='review_count',
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='quiz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempt', to='quiz.quiz'),
        ),
    ]
