# Generated by Django 5.0.2 on 2025-05-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_wronganswernote_review_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wronganswernote',
            name='is_mastered',
            field=models.BooleanField(default=False),
        ),
    ]
