# Generated by Django 5.0.2 on 2025-05-26 03:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_wronganswernote_is_mastered'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('user', 'quiz_type', 'mode', 'completed_at')},
        ),
    ]
