# Generated by Django 5.0.2 on 2025-05-14 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        ('vocabulary', '0004_alter_word_options_alter_word_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', '초급'), ('intermediate', '중급'), ('advanced', '고급')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', '객관식'), ('word_meaning', '단어 의미'), ('sentence_completion', '문장 완성'), ('context_usage', '문맥 속 사용')], max_length=20)),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(max_length=200)),
                ('options', models.JSONField(help_text='객관식 문제의 보기')),
                ('explanation', models.TextField(blank=True)),
                ('points', models.IntegerField(default=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='study.leveltest')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='vocabulary.word')),
            ],
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(choices=[(1, 'Level 1 - 기초'), (2, 'Level 2 - 초급'), (3, 'Level 3 - 중급'), (4, 'Level 4 - 중상급'), (5, 'Level 5 - 고급')])),
                ('last_test_date', models.DateTimeField(auto_now=True)),
                ('recommended_words_per_day', models.IntegerField(default=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('level', models.IntegerField(choices=[(1, 'Level 1 - 기초'), (2, 'Level 2 - 초급'), (3, 'Level 3 - 중급'), (4, 'Level 4 - 중상급'), (5, 'Level 5 - 고급')])),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('answers', models.JSONField(help_text='사용자의 답변 기록')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.leveltest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
