# Generated by Django 5.0.2 on 2025-05-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_leveltest_testquestion_userlevel_usertestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='difficulty',
            field=models.CharField(choices=[('easy', '초급'), ('medium', '중급'), ('hard', '고급')], default='easy', max_length=10),
        ),
    ]
