# Generated by Django 5.0.2 on 2025-05-20 12:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_studynotification_dailygoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogress',
            name='last_reviewed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
