# Generated by Django 5.0.2 on 2025-05-25 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_dailymissionmodalshown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='study_minutes',
            field=models.FloatField(default=0),
        ),
    ]
