# Generated by Django 5.0.2 on 2025-05-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_alter_studysession_study_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='daily_study_time',
            field=models.FloatField(default=0),
        ),
    ]
