# Generated by Django 5.0.2 on 2025-05-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0011_studysession_daily_study_time'),
        ('vocabulary', '0008_personalwordlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studysession',
            old_name='daily_study_time',
            new_name='daily_study_minutes',
        ),
        migrations.AddField(
            model_name='studysession',
            name='words',
            field=models.ManyToManyField(through='study.StudyProgress', to='vocabulary.word'),
        ),
    ]
