# Generated by Django 5.0.2 on 2025-03-21 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리 목록',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100, verbose_name='영단어')),
                ('korean', models.CharField(max_length=200, verbose_name='한글 뜻')),
                ('pronunciation', models.CharField(blank=True, max_length=100, verbose_name='발음')),
                ('part_of_speech', models.CharField(blank=True, max_length=50, verbose_name='품사')),
                ('difficulty', models.CharField(choices=[('easy', '쉬움'), ('medium', '보통'), ('hard', '어려움')], default='medium', max_length=10, verbose_name='난이도')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='vocabulary.category')),
            ],
            options={
                'verbose_name': '단어',
                'verbose_name_plural': '단어 목록',
                'ordering': ['english'],
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.TextField(verbose_name='영어 예문')),
                ('korean', models.TextField(verbose_name='한글 해석')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='vocabulary.word')),
            ],
            options={
                'verbose_name': '예문',
                'verbose_name_plural': '예문 목록',
            },
        ),
        migrations.CreateModel(
            name='WordStudyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답 여부')),
                ('studied_at', models.DateTimeField(auto_now_add=True, verbose_name='학습일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_histories', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_histories', to='vocabulary.word')),
            ],
            options={
                'verbose_name': '학습 이력',
                'verbose_name_plural': '학습 이력 목록',
                'ordering': ['-studied_at'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='vocabulary.word')),
            ],
            options={
                'verbose_name': '북마크',
                'verbose_name_plural': '북마크 목록',
                'unique_together': {('user', 'word')},
            },
        ),
    ]
