# Generated by Django 5.0.2 on 2025-03-21 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['-created_at'], 'verbose_name': '단어', 'verbose_name_plural': '단어 목록'},
        ),
        migrations.AlterModelOptions(
            name='wordstudyhistory',
            options={'ordering': ['-studied_at'], 'verbose_name': '학습 기록', 'verbose_name_plural': '학습 기록 목록'},
        ),
        migrations.RemoveField(
            model_name='word',
            name='category',
        ),
        migrations.RemoveField(
            model_name='word',
            name='pronunciation',
        ),
        migrations.AddField(
            model_name='word',
            name='example_sentence',
            field=models.TextField(blank=True, verbose_name='예문'),
        ),
        migrations.AddField(
            model_name='word',
            name='example_translation',
            field=models.TextField(blank=True, verbose_name='예문 번역'),
        ),
        migrations.AlterField(
            model_name='word',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(max_length=50, verbose_name='품사'),
        ),
        migrations.AlterField(
            model_name='wordstudyhistory',
            name='studied_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='학습 일시'),
        ),
        migrations.AlterField(
            model_name='wordstudyhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wordstudyhistory',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_history', to='vocabulary.word'),
        ),
        migrations.CreateModel(
            name='WordBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='북마크 일시')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='vocabulary.word')),
            ],
            options={
                'verbose_name': '단어 북마크',
                'verbose_name_plural': '단어 북마크 목록',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'word')},
            },
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
