# Generated by Django 5.0.2 on 2025-03-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_word_options_alter_wordstudyhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', '명사'), ('verb', '동사'), ('adjective', '형용사'), ('adverb', '부사'), ('preposition', '전치사'), ('conjunction', '접속사'), ('interjection', '감탄사')], max_length=50, verbose_name='품사'),
        ),
    ]
