# Generated by Django 5.0.2 on 2025-03-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_alter_word_part_of_speech'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['english'], 'verbose_name': '단어', 'verbose_name_plural': '단어 목록'},
        ),
        migrations.AlterField(
            model_name='word',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(max_length=100, verbose_name='영어'),
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', '명사'), ('verb', '동사'), ('adjective', '형용사'), ('adverb', '부사'), ('preposition', '전치사'), ('conjunction', '접속사'), ('pronoun', '대명사'), ('interjection', '감탄사'), ('article', '관사'), ('other', '기타')], default='noun', max_length=20, verbose_name='품사'),
        ),
        migrations.DeleteModel(
            name='WordStudyHistory',
        ),
    ]
