# Generated by Django 5.0.2 on 2025-05-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0004_alter_word_options_alter_word_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_todays_word',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='difficulty',
            field=models.CharField(choices=[('easy', '쉬움'), ('medium', '보통'), ('hard', '어려움')], max_length=20),
        ),
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='example_sentence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='example_translation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='korean',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='word',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
