# Generated by Django 5.0.2 on 2025-05-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0005_word_is_todays_word_word_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='is_todays_word',
        ),
        migrations.RemoveField(
            model_name='word',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='word',
            name='daily_word_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
        migrations.AlterField(
            model_name='word',
            name='difficulty',
            field=models.CharField(choices=[('easy', '쉬움'), ('medium', '보통'), ('hard', '어려움')], default='medium', max_length=10, verbose_name='난이도'),
        ),
        migrations.AlterField(
            model_name='word',
            name='english',
            field=models.CharField(max_length=100, verbose_name='영어'),
        ),
        migrations.AlterField(
            model_name='word',
            name='example_sentence',
            field=models.TextField(blank=True, null=True, verbose_name='예문'),
        ),
        migrations.AlterField(
            model_name='word',
            name='example_translation',
            field=models.TextField(blank=True, null=True, verbose_name='예문 번역'),
        ),
        migrations.AlterField(
            model_name='word',
            name='korean',
            field=models.CharField(max_length=200, verbose_name='한글 뜻'),
        ),
        migrations.AlterField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(choices=[('noun', '명사'), ('verb', '동사'), ('adjective', '형용사'), ('adverb', '부사'), ('preposition', '전치사'), ('conjunction', '접속사'), ('pronoun', '대명사'), ('interjection', '감탄사'), ('article', '관사'), ('other', '기타')], default='noun', max_length=20, verbose_name='품사'),
        ),
        migrations.AlterField(
            model_name='word',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
    ]
