# Generated by Django 5.0.2 on 2025-05-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0006_remove_word_is_todays_word_remove_word_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_bookmarked',
            field=models.BooleanField(default=False, verbose_name='즐겨찾기'),
        ),
    ]
