# Generated by Django 5.0.2 on 2025-05-20 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0007_word_is_bookmarked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalWordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가 일시')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_word_lists', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_lists', to='vocabulary.word')),
            ],
            options={
                'verbose_name': '개인 단어장',
                'verbose_name_plural': '개인 단어장 목록',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
